### ISSUE TITLE
Build error (Xcode 14.1). Non-Intel Homebrew path.

### ISSUE THREAD

**Issue by macbugs** [textbrowser/spot-on-lite#1]
[_"Spot-On-Lite compiles on Debian, Mac OS X, and OpenBSD."_](https://github.com/textbrowser/spot-on-lite)
`
Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++`
```
warning: unknown warning option '-Wformat-overflow=2'; did you mean '-Wshift-overflow'? [-Wunknown-warning-option]
warning: unknown warning option '-Wformat-truncation=2' [-Wunknown-warning-option]
Source/spot-on-lite-daemon-child.cc:37:10: fatal error: 'openssl/pem.h' file not found
#include <openssl/pem.h>
```

_"- Windows? Yuck!"_ 😆

**Comment by textbrowser** [comment]
You're missing OpenSSL development files.

**Comment by textbrowser** [comment]
https://github.com/textbrowser/spot-on-lite/commit/890b54009c061f2d5677750573804196b868b713

:P

**Comment by textbrowser** [comment]
And thanks you for the ticket.

**Comment by macbugs** [comment]
![Screenshot 2022-12-04 at 13 35 27](https://user-images.githubusercontent.com/101867641/205509029-c6909ca7-3c90-4527-a856-4334a1bd22dc.png)
```
% openssl version
LibreSSL 3.3.6
```
https://stackoverflow.com/a/63076154

**Comment by textbrowser** [comment]
And mentioned elsewhere, I have /usr/local/opt which links to Cellar. I didn't create the symbolic link. I don't follow HB with their numerous updates. I can add another test for /usr/local/Cellar. I don't have /opt/homebrew.

**Comment by textbrowser** [comment]
From 2018.

https://osxdaily.com/2018/07/05/where-homebrew-packages-installed-location-mac/

**Comment by textbrowser** [comment]
https://docs.brew.sh/Installation

**Comment by textbrowser** [comment]
Anyway, OpenSSL is optional.

**Comment by textbrowser** [comment]
OK, this request is for non-Intel.

**Comment by textbrowser** [comment]
Please donate $100,000 for an Apple laptop.

**Comment by macbugs** [comment]
...just a notation for general reference...
`% brew info openssl`

```
==> openssl@3: stable 3.0.7 (bottled) [keg-only]
/opt/homebrew/Cellar/openssl@3/3.0.7 (6,454 files, 28.0MB)
  Poured from bottle on 2022-11-16 at 08:52:58

openssl@3 is keg-only, which means it was not symlinked into /opt/homebrew,
because macOS provides LibreSSL.

If you need to have openssl@3 first in your PATH, run:
  echo 'export PATH="/opt/homebrew/opt/openssl@3/bin:$PATH"' >> ~/.zshrc

For compilers to find openssl@3 you may need to set:
  export LDFLAGS="-L/opt/homebrew/opt/openssl@3/lib"
  export CPPFLAGS="-I/opt/homebrew/opt/openssl@3/include"

For pkg-config to find openssl@3 you may need to set:
  export PKG_CONFIG_PATH="/opt/homebrew/opt/openssl@3/lib/pkgconfig"
```
ok, moving along to the next thing...
```
Source/spot-on-lite-daemon-child.cc:98:12: warning: unused variable 's_certificate_version' [-Wunused-variable]
static int s_certificate_version = 2; // TLS 1.3 is sensitive.
```
```
-F/opt/homebrew/lib -lcrypto -lssl -framework QtGui -framework AppKit -framework ImageIO -framework Metal -framework QtNetwork -framework QtSql -framework QtConcurrent -framework QtCore -framework IOKit -framework DiskArbitration -framework AGL -framework OpenGL

ld: library not found for -lcrypto
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [Spot-On-Lite-Daemon] Error 1
make: *** [all] Error 2
```

> _**Please donate $100,000 for an Apple laptop.**_

_mon dieu_, is that really current market price ?

**Comment by textbrowser** [comment]
Noooooooooooooooooo. Soon will be.

**Comment by textbrowser** [comment]
The compilation may complete now. I don't know if Spot-On-Lite-Monitor does.

**Comment by textbrowser** [comment]
Does work, that is.

**Comment by textbrowser** [comment]
And of course fork() is weird on Mac.

**Comment by macbugs** [comment]
https://github.com/textbrowser/spot-on-lite/commit/890b54009c061f2d5677750573804196b868b713 [😂](https://www.youtube.com/watch?v=6p-lDYPR2P8#t=31s)
```
install -d --group=staff /usr/local/spot-on-lite

install: illegal option -- -
usage: install [-bCcpSsv] [-B suffix] [-f flags] [-g group] [-m mode]
               [-o owner] file1 file2
       install [-bCcpSsv] [-B suffix] [-f flags] [-g group] [-m mode]
               [-o owner] file1 ... fileN directory
       install -d [-v] [-g group] [-m mode] [-o owner] directory ...
make: *** [install] Error 64
```

> _**[The lowercase "d" should work. If it doesn't, you can install GNU install with Homebrew coreutils which will provide the "D" flag.](https://apple.stackexchange.com/questions/201029/install-illegal-option-d)**_

```
==> Downloading https://ghcr.io/v2/homebrew/core/coreutils/manifests/9.1
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/coreutils/blobs/sha256:ae9dc313da2a3971c8e633d9f3262fd1bd431c303207b3346924aed60bb0965d
==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sha256:ae9dc313da2a3971c8e633d9f3262fd1bd431c303207b3346924aed60bb0965d?se=2022-12-04T22%3A35%3A00Z&sig=Uq6fVrSBEzNkaz3wD0KolCXaF640bQ%2F1CsZ
######################################################################## 100.0%
==> Pouring coreutils--9.1.arm64_ventura.bottle.tar.gz
==> Caveats
Commands also provided by macOS and the commands dir, dircolors, vdir have been installed with the prefix "g".
If you need to use these commands with their normal names, you can add a "gnubin" directory to your PATH with:
  PATH="/opt/homebrew/opt/coreutils/libexec/gnubin:$PATH"
==> Summary
🍺  /opt/homebrew/Cellar/coreutils/9.1: 476 files, 13.2MB
```

**Comment by textbrowser** [comment]
Why do you want to install it?

**Comment by textbrowser** [comment]
Yes, Mac is ugly.

**Comment by textbrowser** [comment]
https://developer.apple.com/library/archive/documentation/MacOSX/Conceptual/BPSystemStartup/Chapters/CreatingLaunchdJobs.html

**Comment by textbrowser** [comment]
That's just wrong.

"You must not [daemon](https://developer.apple.com/library/archive/documentation/System/Conceptual/ManPages_iPhoneOS/man3/daemon.3.html#//apple_ref/doc/man/3/daemon)ize your process. This includes calling the daemon function, calling fork followed by [exec](https://developer.apple.com/library/archive/documentation/System/Conceptual/ManPages_iPhoneOS/man3/exec.3.html#//apple_ref/doc/man/3/exec), or calling fork followed by [exit](https://developer.apple.com/library/archive/documentation/System/Conceptual/ManPages_iPhoneOS/man3/exit.3.html#//apple_ref/doc/man/3/exit). If you do, launchd thinks your process has died. Depending on your property list key settings, launchd will either keep trying to relaunch your process until it gives up (with a “respawning too fast” error message) or will be unable to restart it if it really does die."

**Comment by textbrowser** [comment]
> [890b540](https://github.com/textbrowser/spot-on-lite/commit/890b54009c061f2d5677750573804196b868b713) [joy](https://www.youtube.com/watch?v=6p-lDYPR2P8#t=31s)
> 
> ```
> install -d --group=staff /usr/local/spot-on-lite
> 
> install: illegal option -- -
> usage: install [-bCcpSsv] [-B suffix] [-f flags] [-g group] [-m mode]
>                [-o owner] file1 file2
>        install [-bCcpSsv] [-B suffix] [-f flags] [-g group] [-m mode]
>                [-o owner] file1 ... fileN directory
>        install -d [-v] [-g group] [-m mode] [-o owner] directory ...
> make: *** [install] Error 64
> ```
> 
> > _**[The lowercase "d" should work. If it doesn't, you can install GNU install with Homebrew coreutils which will provide the "D" flag.](https://apple.stackexchange.com/questions/201029/install-illegal-option-d)**_
> 
> ```
> ==> Downloading https://ghcr.io/v2/homebrew/core/coreutils/manifests/9.1
> ######################################################################## 100.0%
> ==> Downloading https://ghcr.io/v2/homebrew/core/coreutils/blobs/sha256:ae9dc313da2a3971c8e633d9f3262fd1bd431c303207b3346924aed60bb0965d
> ==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sha256:ae9dc313da2a3971c8e633d9f3262fd1bd431c303207b3346924aed60bb0965d?se=2022-12-04T22%3A35%3A00Z&sig=Uq6fVrSBEzNkaz3wD0KolCXaF640bQ%2F1CsZ
> ######################################################################## 100.0%
> ==> Pouring coreutils--9.1.arm64_ventura.bottle.tar.gz
> ==> Caveats
> Commands also provided by macOS and the commands dir, dircolors, vdir have been installed with the prefix "g".
> If you need to use these commands with their normal names, you can add a "gnubin" directory to your PATH with:
>   PATH="/opt/homebrew/opt/coreutils/libexec/gnubin:$PATH"
> ==> Summary
> 🍺  /opt/homebrew/Cellar/coreutils/9.1: 476 files, 13.2MB
> ```

Oh yes. I'll remove the install target. I've never, ever applied it.

**Comment by macbugs** [comment]
> _**That's just wrong.**_

Yes, okay, I encounter that issue often enough.

> _**this request is for non-Intel.**_

Just teasing a little, because `readme.md` says _"Debian, FreeBSD, Mac, OpenBSD."_ 
I acknowledge your complaints about Mac OS.  So where can you get [$100k](https://www.imdb.com/title/tt5330088/)… [?](https://www.indeed.com/cmp/Google/salaries/Programmer)

> _**Oh yes. I'll remove the install target. I've never, ever applied it.**_

Dont forget to write some usage instructions and a screenshot of the GUI [here](https://textbrowser.github.io/spot-on-lite/).
___
...some script packaging tools that might be useful some time…

https://gist.github.com/oubiwann/453744744da1141ccc542ff75b47e0cf
https://gist.github.com/mathiasbynens/674099
https://sveinbjorn.org/platypus

**Comment by textbrowser** [comment]
It was functional at some point on Mac and I usually test the non-daemon mode locally. Now it launches, but the openssl utility does not complete the SSL handshake on Mac. Oh wait. Perhaps I need to test the non-Mac openssl utility.

**Comment by textbrowser** [comment]
There is a monitor application included. I don't launch it because there's a terminal option for displaying statistics.

**Comment by textbrowser** [comment]
You can see an example in the README.md file.

**Comment by textbrowser** [comment]
Works with the Brew's OpenSSL utility. Closing!

**Comment by textbrowser** [comment]
On Mac with remote connection.

https://github.com/textbrowser/spot-on-lite

**Comment by textbrowser** [comment]
https://github.com/textbrowser/spot-on-lite/releases

:)

**Comment by textbrowser** [comment]
Thanks for your contributions.
