### ISSUE TITLE
Projects uses Qt5, but it is broken for macOS PPC

### ISSUE THREAD

**Issue by barracuda156** [textbrowser/spot-on-lite#2]
There is no functional Qt5 for macOS PPC presently. It does not build.
If PPC is supported, Qt4 should be used instead for it.

**Comment by textbrowser** [comment]
I know it works for PPC Debian because I've tested it. I will retest it. As for MacOS PPC and Qt 4, that's not going to happen. SO-Lite is Qt 5 and 6. Qt 4 is long dead.

**Comment by textbrowser** [comment]
Qt 4 is not supported by Qt. It is full of unknown errors.

**Comment by barracuda156** [comment]
> Qt 4 is not supported by Qt. It is full of unknown errors.

It is not currently supported by upstream, but it works perfectly fine and builds on every system including the latest ones: https://ports.macports.org/port/qt4-mac/details (Big Sur arm64 seems to be the only exception).

**Comment by textbrowser** [comment]
I don't have a MacOS PPC, just a Mac PPC. I also don't have an interest in porting SO-Lite to Qt 4. Qt 4 is less than pleasant. I also don't have a Qt 4 test platform so there's that.

**Comment by barracuda156** [comment]
Just in case, if any testing will be needed, I can do it on 10.5.8 (ppc/ppc64), 10.6 (ppc) and 10.6.8 (ppc via Rosetta).

**Comment by textbrowser** [comment]
How do you propose that? I cannot compile it unless I have a Qt 4 platform. Those are rare and I'm not about to install Qt 4. You'll have to port it on your own and determine if your changes can be easily merged.

I ported the Qt 5 logic to Qt 6 and that was an effort. I don't see the benefit of porting it to Qt 4 other than for you. After that, I cannot maintain it because, again, I don't have a Qt 4 platform.

Why is this an interest? SO-Lite is a daemon. It's not Spot-On. :P

**Comment by textbrowser** [comment]
If you're committed, I'll guide you with the port. But only if you're committed!

**Comment by textbrowser** [comment]
I attempted a build in CentOS 6.10. Eliminated newer compiler options. Began the build. Massive and complex failures. A port is effectively a new application. Closing.

**Comment by barracuda156** [comment]
> I attempted a build in CentOS 6.10. Eliminated newer compiler options. Began the build. Massive and complex failures. A port is effectively a new application. Closing.

@textbrowser Got it. Thank you for trying!

**Comment by textbrowser** [comment]
For example, C++11 is required. Not available in CentOS 6.10. Is it available in MacOS PPC? That would help eliminate some of the errors.

**Comment by barracuda156** [comment]
> For example, C++11 is required. Not available in CentOS 6.10. Is it available in MacOS PPC? That would help eliminate some of the errors.

Yes, sure. Everything up to C++17 is supported on all archs, including PowerPC. `Qt5` is the only stopper.

**Comment by textbrowser** [comment]
The port may not be that difficult depending on Qt 5 and 6 things. I've abandoned Qt 4 on most of my Qt applications. It's a lot of work supporting 4, 5, 6. 3 major releases. I'm not Microsoft.

**Comment by textbrowser** [comment]
OpenBSD and perhaps NetBSD continue to support PowerPC. Debian dropped it. FreeBSD kind of supports it. There is also Gentoo and some weirder distributions. It's kind of a specialty architecture with nostalgic people.

**Comment by textbrowser** [comment]
I could not find published reports regarding PowerPC hardware vulnerabilities. I'd consider that aspect. Also, the older hardware is not very efficient in terms of electricity. Why are you interested in PowerPC?

**Comment by barracuda156** [comment]
> The port may not be that difficult depending on Qt 5 and 6 things. I've abandoned Qt 4 on most of my Qt applications. It's a lot of work supporting 4, 5, 6. 3 major releases. I'm not Microsoft.

Yeah I realize that. Not really trying to convince you here, it obviously depends on amount of work involved. Since it is time-consuming, makes no sense to waste time on that.

**Comment by barracuda156** [comment]
> I could not find published reports regarding PowerPC hardware vulnerabilities. I'd consider that aspect. Also, the older hardware is not very efficient in terms of electricity. Why are you interested in PowerPC?

Well, I have some PPC hardware and like it, and Macports supports macOS PPC. (And yeah, FreeBSD kinda supports it too.)

Basically I was just browsing Guthub looking for projects which explicitly support PPC and look interesting to bring them into Macports. If description had something like Linux PPC, I would not open an issue.

**Comment by textbrowser** [comment]
It works in Qt 5.5.1. :) That's probably the oldest Qt 5 that I support.

Would be splendid if Mac Ports gets Qt 5 working. But then, that's being deprecated too.

**Comment by barracuda156** [comment]
> Would be splendid if Mac Ports gets Qt 5 working. But then, that's being deprecated too.

It works on 10.6.8 Intel and later in Macports. So far no one had time to fix it for PPC (likely 10.5.8 Intel is also broken, but I did not verify that).

**Comment by textbrowser** [comment]
It's a huge project, Qt.

**Comment by barracuda156** [comment]
> It's a huge project, Qt.

Precisely for that reason. It is desirable, but huge.
